<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="Mac" failures="1" tests="8" name="Surefire test" time="42.116" errors="0" timestamp="2025-03-08T19:25:30 AST">
  <testcase classname="VisualPerformanceTests.VisualPerformanceTest" name="testVisualAndPerformance" time="4.934"/>
  <testcase classname="ApiUiValidationTests.ApiUiValidationTest" name="testApiUiValidation" time="1.195"/>
  <testcase classname="SauceDemoTests.CheckoutTest" name="testCheckoutWorkflow" time="1.465"/>
  <testcase classname="SauceDemoTests.ProductDTOFilterTest" name="testProductSortingAndCartVerification" time="1.325"/>
  <testcase classname="SauceDemoTests.LoginTests" name="loginTests" time="0.259"/>
  <testcase classname="SauceDemoTests.LoginTests" name="loginTests" time="0.597">
    <failure type="java.lang.AssertionError" message="The following asserts failed:
	Expected: Error Message: &amp;quot;Sorry, this user has been locked out.&amp;quot; but got: Epic sadface: Sorry, this user has been locked out. expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: The following asserts failed:
Expected: Error Message: "Sorry, this user has been locked out." but got: Epic sadface: Sorry, this user has been locked out. expected [true] but found [false]
at SauceDemoTests.LoginTests.loginTests(LoginTests.java:58)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 32 stack frames]]>
    </failure>
  </testcase> <!-- loginTests -->
  <testcase classname="SauceDemoTests.LoginTests" name="loginTests" time="1.084"/>
  <testcase classname="SauceDemoTests.LoginTests" name="loginTests" time="5.344"/>
</testsuite> <!-- Surefire test -->
